"""Themed sets / mini-stories (Batch 2).

A mini-story is a short, themed sequence of linked exercises that share a single everyday
narrative (e.g. "moving to a new apartment"). Scenarios are deliberately universal so the app
fits any learner, not only developers. The narrative scaffolding — title, intro and per-beat
narration — is curated *here in code*, not produced by the model. Each beat's exercise is
generated by the existing validated per-type generators (`grammar.generate_exercise`); if the
caller passes `context_override` (the learner's field), the exercises are flavored toward that
field while the story frame stays universal. Quality stays reliable on a small local model and the
story structure is independent of the model in use.

Grading is unchanged: every beat carries its own Fernet-sealed token graded by `POST /check`.
"""

from __future__ import annotations

import random
from typing import Any

from . import grammar

# Curated scenarios. `topics` must use the canonical backend topic names (grammar.TOPICS); a beat
# whose topic isn't recognised falls back to the generator's weighted pick. `narration` has one line
# per beat (we serve STORY_LEN beats), threading the story between exercises. `context` is the shared
# scenario string fed to every beat's generator.
STORY_LEN = 3

SCENARIOS: list[dict[str, Any]] = [
    {
        "id": "moving-day",
        "title": "The big move",
        "intro": "Saturday morning. The moving van arrives early and there are still half-packed "
        "boxes in every room. You and a friend get to work.",
        "context": "a person moving to a new apartment over the weekend",
        "topics": ["conditionals", "verb sequence (tense agreement)", "modal verbs"],
        "narration": [
            "The boxes pile up faster than you expected.",
            "You try to remember where you packed the kettle.",
            "Your friend asks what you should do with the old sofa.",
        ],
    },
    {
        "id": "missing-bag",
        "title": "The missing bag",
        "intro": "You land after a long flight, but your suitcase never appears on the belt. You "
        "head to the airline desk to sort it out.",
        "context": "a traveller reporting a lost suitcase at the airport",
        "topics": ["articles", "prepositions", "word order"],
        "narration": [
            "You describe which bag is yours to the agent.",
            "The agent asks where you flew from and when.",
            "They promise to deliver it, so you fill in your address.",
        ],
    },
    {
        "id": "first-day",
        "title": "First day",
        "intro": "First day at a new place. A friendly colleague shows you around over a cup of "
        "coffee and a very long welcome guide.",
        "context": "a person on their first day at a new job, meeting the team",
        "topics": ["phrasal verbs", "prepositions", "gerunds & infinitives"],
        "narration": [
            "Your colleague explains how everything fits together.",
            "You settle in at your desk and sort out a few small problems.",
            "By lunch you're ready to start your first task.",
        ],
    },
    {
        "id": "the-deadline",
        "title": "The deadline",
        "intro": "The big project is due tomorrow and a few things still aren't finished. The team "
        "gathers to decide how to get it over the line.",
        "context": "a team working against a tight deadline on an important project",
        "topics": ["verb sequence (tense agreement)", "modal verbs", "comparatives & superlatives"],
        "narration": [
            "You describe what happened earlier in the day.",
            "The team weighs two possible plans against each other.",
            "You agree on the safer option and note what to do next.",
        ],
    },
]


async def build_story(level: str | None = None, context_override: str | None = None) -> dict[str, Any]:
    """Assemble a mini-story: pick a curated scenario, then generate one exercise per beat.

    Each exercise is produced by `grammar.generate_exercise` (its own 3-retry + multiple-choice
    fallback), so a single bad generation degrades to a simpler card rather than breaking the set.
    `level` is locked across the whole story; the per-beat topic varies across the scenario's topics
    so the set isn't monotonous. `context_override`, if given, replaces the scenario's flavor context.
    """
    scenario = random.choice(SCENARIOS)
    context = context_override or scenario["context"]
    topics = scenario["topics"]

    beats: list[dict[str, Any]] = []
    for i in range(STORY_LEN):
        topic = topics[i % len(topics)]
        exercise = await grammar.generate_exercise(
            topic=topic, level=level, ex_type=None, context=context
        )
        narration = scenario["narration"][i] if i < len(scenario["narration"]) else ""
        beats.append({"narration": narration, "exercise": exercise})

    return {
        "id": scenario["id"],
        "title": scenario["title"],
        "intro": scenario["intro"],
        "level": grammar._cefr(level),
        "beats": beats,
    }
