"""Themed sets / mini-stories (Batch 2).

A mini-story is a short, themed sequence of linked exercises that share a single everyday
narrative (e.g. "moving to a new apartment"). Scenarios are deliberately universal so the app
fits any learner, not only developers. The narrative scaffolding — title, intro and per-beat
narration — is curated *here in code*, not produced by the model. Each beat's exercise is
generated by the existing validated per-type generators (`grammar.generate_exercise`); if the
caller passes `context_override` (the learner's field), the exercises are flavored toward that
field while the story frame stays universal. Quality stays reliable on a small local model and the
story structure is independent of the model in use.

Grading is unchanged: every beat carries its own Fernet-sealed token graded by `POST /check`.
"""

from __future__ import annotations

import asyncio
import hashlib
import random
from typing import Any

from . import grammar

# Curated scenarios. `topics` must use the canonical backend topic names (grammar.TOPICS); a beat
# whose topic isn't recognised falls back to the generator's weighted pick. `narration` has one line
# per beat (we serve STORY_LEN beats), threading the story between exercises. `context` is the shared
# scenario string fed to every beat's generator.
STORY_LEN = 3

SCENARIOS: list[dict[str, Any]] = [
    {
        "id": "moving-day",
        "title": "The big move",
        "intro": "Saturday morning. The moving van arrives early and there are still half-packed "
        "boxes in every room. You and a friend get to work.",
        "context": "a person moving to a new apartment over the weekend",
        "topics": ["conditionals", "verb sequence (tense agreement)", "modal verbs"],
        "narration": [
            "The boxes pile up faster than you expected.",
            "You try to remember where you packed the kettle.",
            "Your friend asks what you should do with the old sofa.",
        ],
    },
    {
        "id": "missing-bag",
        "title": "The missing bag",
        "intro": "You land after a long flight, but your suitcase never appears on the belt. You "
        "head to the airline desk to sort it out.",
        "context": "a traveller reporting a lost suitcase at the airport",
        "topics": ["articles", "prepositions", "word order"],
        "narration": [
            "You describe which bag is yours to the agent.",
            "The agent asks where you flew from and when.",
            "They promise to deliver it, so you fill in your address.",
        ],
    },
    {
        "id": "first-day",
        "title": "First day",
        "intro": "First day at a new place. A friendly colleague shows you around over a cup of "
        "coffee and a very long welcome guide.",
        "context": "a person on their first day at a new job, meeting the team",
        "topics": ["phrasal verbs", "prepositions", "gerunds & infinitives"],
        "narration": [
            "Your colleague explains how everything fits together.",
            "You settle in at your desk and sort out a few small problems.",
            "By lunch you're ready to start your first task.",
        ],
    },
    {
        "id": "the-deadline",
        "title": "The deadline",
        "intro": "The big project is due tomorrow and a few things still aren't finished. The team "
        "gathers to decide how to get it over the line.",
        "context": "a team working against a tight deadline on an important project",
        "topics": ["verb sequence (tense agreement)", "modal verbs", "comparatives & superlatives"],
        "narration": [
            "You describe what happened earlier in the day.",
            "The team weighs two possible plans against each other.",
            "You agree on the safer option and note what to do next.",
        ],
    },
    {
        "id": "market-day",
        "title": "Market day",
        "intro": "The Saturday market is loud and full. You have a short list, a little cash, and a "
        "stallholder who loves to bargain.",
        "context": "a person shopping and bargaining at a busy street market",
        "topics": ["articles", "comparatives & superlatives", "prepositions"],
        "narration": [
            "You compare two stalls selling the same fruit.",
            "The seller offers a better price if you buy more.",
            "You pack your bag and head for the last item on the list.",
        ],
    },
    {
        "id": "the-interview",
        "title": "The interview",
        "intro": "A job you really want. You arrive early, rehearse your answers one last time, and "
        "wait for your name to be called.",
        "context": "a candidate at a job interview for a role they want",
        "topics": ["verb sequence (tense agreement)", "modal verbs", "gerunds & infinitives"],
        "narration": [
            "You explain what you did in your last role.",
            "They ask how you would handle a tricky situation.",
            "You ask a thoughtful question of your own to close.",
        ],
    },
    {
        "id": "the-recipe",
        "title": "The recipe",
        "intro": "Friends are coming for dinner and you're trying a new recipe for the first time. "
        "The kitchen is warm, the timer is ticking, and the instructions are long.",
        "context": "a person cooking a new recipe at home for friends",
        "topics": ["gerunds & infinitives", "prepositions", "verb sequence (tense agreement)"],
        "narration": [
            "You read through the recipe before you start cooking.",
            "You add the ingredients in the right order, step by step.",
            "While the dish bakes, you set the table for your guests.",
        ],
    },
    {
        "id": "the-roadtrip",
        "title": "The road trip",
        "intro": "Two friends, a full tank, and a loose plan. The map is open on your knees and the "
        "coast is somewhere at the end of the day.",
        "context": "two friends on a long road trip with a loose plan",
        "topics": ["modal verbs", "comparatives & superlatives", "prepositions"],
        "narration": [
            "You pick the route that looks more scenic than the highway.",
            "Halfway there, you have to stop for fuel and snacks.",
            "By evening you reach the coast and look for a place to stay.",
        ],
    },
    {
        "id": "the-garden",
        "title": "The garden",
        "intro": "First warm weekend of spring. The soil is soft, the seed packets are spread on the "
        "step, and you finally have a free afternoon to plant something.",
        "context": "a person starting a small garden on a spring weekend",
        "topics": ["gerunds & infinitives", "prepositions", "modal verbs"],
        "narration": [
            "You decide which seeds to plant along the back fence.",
            "You dig the beds and water the soil before sundown.",
            "You should label each row, or you'll forget what's where.",
        ],
    },
    {
        "id": "the-power-cut",
        "title": "The power cut",
        "intro": "The lights flicker once, then everything goes dark. The fridge hums to silence and "
        "you reach for your phone to see what's going on.",
        "context": "a person dealing with a sudden blackout at home",
        "topics": ["conditionals", "modal verbs", "word order"],
        "narration": [
            "You feel your way to the drawer where the candles are.",
            "If the power stays off, the food in the freezer will spoil.",
            "You check on the neighbours and share a spare torch.",
        ],
    },
    {
        "id": "the-lost-dog",
        "title": "The lost dog",
        "intro": "The back gate was left open and now the dog is gone. You grab the lead and a handful "
        "of treats and start asking everyone on the street.",
        "context": "a person searching the neighbourhood for a lost dog",
        "topics": ["verb sequence (tense agreement)", "prepositions", "articles"],
        "narration": [
            "You describe the dog to a jogger near the park.",
            "Someone says they saw a small dog by the river an hour ago.",
            "You follow the trail and call its name down every lane.",
        ],
    },
    {
        "id": "the-new-phone",
        "title": "The new phone",
        "intro": "A shiny box, a tiny screwdriver for the SIM, and a setup screen that asks you a "
        "hundred questions. You settle in to move everything across.",
        "context": "a person setting up a brand-new phone",
        "topics": ["phrasal verbs", "modal verbs", "prepositions"],
        "narration": [
            "You set up the new phone and sign in to your account.",
            "You back up the old photos before you wipe the old device.",
            "You should turn on two-factor login to keep it safe.",
        ],
    },
    {
        "id": "the-late-train",
        "title": "The late train",
        "intro": "The platform clock ticks past the departure time and the board still says 'delayed'. "
        "A small crowd waits, coffee in hand, watching the empty track.",
        "context": "a commuter waiting for a delayed train at the station",
        "topics": ["comparatives & superlatives", "prepositions", "verb sequence (tense agreement)"],
        "narration": [
            "The next train is slower but it leaves from a closer platform.",
            "You ask the guard which service will arrive first.",
            "You decide to wait, since the express had already left.",
        ],
    },
    {
        "id": "the-birthday-surprise",
        "title": "The surprise party",
        "intro": "Balloons hidden in the closet, a cake in the boot of the car, and twelve people who "
        "must stay quiet. You're in charge of keeping the secret until eight o'clock.",
        "context": "a person organising a surprise birthday party",
        "topics": ["modal verbs", "conditionals", "punctuation"],
        "narration": [
            "Everyone must arrive before the guest of honour does.",
            "If she suspects anything, the whole surprise is ruined.",
            "You text the group: \"Lights off, stay quiet, she's coming!\"",
        ],
    },
    {
        "id": "the-flat-tyre",
        "title": "The flat tyre",
        "intro": "A loud thump, then a steady wobble. You pull onto the gravel shoulder, switch on the "
        "hazards, and open the boot to find the spare.",
        "context": "a driver changing a flat tyre on the roadside",
        "topics": ["word order", "modal verbs", "prepositions"],
        "narration": [
            "You loosen the bolts before you lift the car with the jack.",
            "You must place the warning triangle behind the car.",
            "You fit the spare and tighten each bolt in turn.",
        ],
    },
    {
        "id": "the-library",
        "title": "The quiet hour",
        "intro": "Rows of tall shelves, a stamped card in your pocket, and one book you've been "
        "meaning to find for weeks. The reading room is warm and very, very quiet.",
        "context": "a person looking for a book in a busy public library",
        "topics": ["articles", "prepositions", "comparatives & superlatives"],
        "narration": [
            "You search the shelves for the book on the top floor.",
            "The librarian points you to a quieter corner to read.",
            "You find an older edition that's far better than the reprint.",
        ],
    },
    {
        "id": "the-haircut",
        "title": "The haircut",
        "intro": "The chair spins to face the mirror, scissors click somewhere behind you, and you try "
        "to explain exactly how short 'just a little' really means.",
        "context": "a person getting a haircut and chatting with the stylist",
        "topics": ["comparatives & superlatives", "modal verbs", "verb sequence (tense agreement)"],
        "narration": [
            "You explain that you'd like it shorter than last time.",
            "The stylist asks how you usually style it in the morning.",
            "You agree the fringe could be a little neater on top.",
        ],
    },
    {
        "id": "the-check-up",
        "title": "The check-up",
        "intro": "A clipboard of questions, a cold stethoscope, and a doctor who actually listens. It's "
        "just a routine visit, but you've saved up a few small worries to ask about.",
        "context": "a person at a routine medical check-up",
        "topics": ["verb sequence (tense agreement)", "modal verbs", "prepositions"],
        "narration": [
            "You describe how you've been feeling over the past month.",
            "The doctor asks whether the pain comes and goes.",
            "You should drink more water and sleep a little earlier.",
        ],
    },
    {
        "id": "the-bake-sale",
        "title": "The bake sale",
        "intro": "Trays of cooling muffins, a hand-painted price sign, and a charity jar that needs "
        "filling by noon. The school hall smells of cinnamon and burnt sugar.",
        "context": "a person running a stall at a charity bake sale",
        "topics": ["articles", "comparatives & superlatives", "prepositions"],
        "narration": [
            "You arrange the cakes so the best ones face the crowd.",
            "A customer asks which slice is the largest for the price.",
            "By noon the jar is fuller than you ever hoped.",
        ],
    },
    {
        "id": "the-camping-trip",
        "title": "The camping trip",
        "intro": "A tent that fought back, a campfire that finally caught, and a sky with more stars "
        "than you've seen in years. The nearest town is an hour down the valley.",
        "context": "two friends on a weekend camping trip in the hills",
        "topics": ["conditionals", "prepositions", "modal verbs"],
        "narration": [
            "You pitch the tent on the flat ground beside the stream.",
            "If it rains tonight, you'll need to move the firewood inside.",
            "You should hang the food high, away from the animals.",
        ],
    },
    {
        "id": "the-job-offer",
        "title": "The offer",
        "intro": "An email you've read four times, a salary line that looks good, and a start date "
        "that's sooner than you expected. You make a coffee and weigh it all up.",
        "context": "a person weighing up a new job offer",
        "topics": ["conditionals", "comparatives & superlatives", "modal verbs"],
        "narration": [
            "You compare the new role with the one you have now.",
            "If you accept, you'd have to move closer to the city.",
            "You decide to ask whether the start date could shift.",
        ],
    },
    {
        "id": "the-flat-hunt",
        "title": "The flat hunt",
        "intro": "Three viewings in one afternoon, a folder of floor plans, and an agent who's always "
        "five minutes late. You're hunting for somewhere that finally feels right.",
        "context": "a person viewing flats to rent in the city",
        "topics": ["comparatives & superlatives", "prepositions", "articles"],
        "narration": [
            "The first flat is brighter but smaller than the second.",
            "You ask the agent how far it is from the station.",
            "You decide the top-floor flat is the best of the three.",
        ],
    },
    {
        "id": "the-snow-day",
        "title": "The snow day",
        "intro": "You wake to a white street, a silent road, and a message that everything's closed. "
        "A rare free day has landed in your lap, and the kettle is already on.",
        "context": "a person enjoying an unexpected snow day at home",
        "topics": ["modal verbs", "conditionals", "word order"],
        "narration": [
            "You decide you might as well stay in and read all day.",
            "If the snow keeps falling, the roads will close by evening.",
            "You make hot chocolate and watch the flakes drift down.",
        ],
    },
    {
        "id": "the-wedding",
        "title": "The big day",
        "intro": "A seating chart that won't stay still, flowers arriving any minute, and a hundred "
        "small jobs before the guests appear. You're helping pull it all together.",
        "context": "a person helping organise a friend's wedding",
        "topics": ["verb sequence (tense agreement)", "modal verbs", "punctuation"],
        "narration": [
            "You check that the caterer had confirmed the final numbers.",
            "The flowers must be on every table before the guests arrive.",
            "You read the schedule aloud: \"Vows at two, photos at three.\"",
        ],
    },
    {
        "id": "the-first-workout",
        "title": "The first workout",
        "intro": "A new gym pass, shoes still squeaky-clean, and a wall of machines you don't quite "
        "recognise. A trainer waves you over to show you the ropes.",
        "context": "a person starting their first week at the gym",
        "topics": ["gerunds & infinitives", "modal verbs", "comparatives & superlatives"],
        "narration": [
            "You start by warming up before you lift anything heavy.",
            "The trainer says you should rest between the harder sets.",
            "By the end you feel stronger than when you walked in.",
        ],
    },
    {
        "id": "the-language-class",
        "title": "The first lesson",
        "intro": "A circle of nervous strangers, a teacher who only speaks the new language, and a "
        "name badge you can barely pronounce. Your first evening class begins.",
        "context": "a person on their first evening at a language class",
        "topics": ["articles", "verb sequence (tense agreement)", "prepositions"],
        "narration": [
            "You introduce yourself and say where you come from.",
            "The teacher asks why you decided to learn the language.",
            "You practise a few phrases with the person beside you.",
        ],
    },
    {
        "id": "the-farmers-market",
        "title": "The farmers' market",
        "intro": "Crates of muddy carrots, a queue for fresh bread, and a tote bag that's already too "
        "heavy. You've a short list and a soft spot for the cheese stall.",
        "context": "a person shopping at a weekend farmers' market",
        "topics": ["comparatives & superlatives", "articles", "prepositions"],
        "narration": [
            "You pick the ripest tomatoes from the corner stall.",
            "The baker asks whether you'd like the larger loaf.",
            "You squeeze past the crowd toward the cheese at the end.",
        ],
    },
    {
        "id": "the-museum-visit",
        "title": "The museum",
        "intro": "Marble floors, a map you keep folding wrong, and three hours to see far too much. "
        "You decide to start with the gallery everyone says you can't miss.",
        "context": "a person spending an afternoon at a large museum",
        "topics": ["prepositions", "articles", "verb sequence (tense agreement)"],
        "narration": [
            "You head for the painting hanging at the top of the stairs.",
            "A guide explains how the artist had worked for years on it.",
            "You wander through the hall toward the ancient coins.",
        ],
    },
    # --- Premium arcs (koku-unlocked, engagement v2 Phase 3). `unlock` = content catalog id. ---
    {
        "id": "midnight-detective",
        "title": "The midnight case",
        "unlock": "arc_detective",
        "intro": "Rain on the window, a cold cup of coffee, and a case that won't close. Tonight the "
        "last clue finally surfaces.",
        "context": "a detective working a mysterious case late at night",
        "topics": ["verb sequence (tense agreement)", "conditionals", "word order"],
        "narration": [
            "You retrace what the witness claimed had happened.",
            "If one detail is true, the whole story changes.",
            "You lay out the order of events and name the culprit.",
        ],
    },
    {
        "id": "orbital-emergency",
        "title": "Orbital emergency",
        "unlock": "arc_space",
        "intro": "Three hundred kilometres up, a warning light starts to blink. The station is quiet, "
        "the checklist is long, and ground control is a radio call away.",
        "context": "an astronaut handling a small emergency on a space station",
        "topics": ["conditionals", "modal verbs", "word order"],
        "narration": [
            "A warning light blinks, and you check what it could mean.",
            "If the pressure keeps dropping, you must seal the module.",
            "You report the fix to ground control in clear, calm words.",
        ],
    },
    {
        "id": "the-verdict",
        "title": "The verdict",
        "unlock": "arc_courtroom",
        "intro": "The courtroom is silent. Every eye is on you as you stand to make the final "
        "argument that could decide the whole case.",
        "context": "a lawyer presenting a case in a tense courtroom",
        "topics": ["verb sequence (tense agreement)", "conditionals", "comparatives & superlatives"],
        "narration": [
            "You summarise what the witness had said earlier.",
            "If the jury believes one fact, the case turns on it.",
            "You make your strongest argument and rest your case.",
        ],
    },
]

# id -> scenario, for O(1) lookup.
_BY_ID = {s["id"]: s for s in SCENARIOS}

# Free scenarios are always available; arcs with an `unlock` need that content id owned.
FREE_IDS = [s["id"] for s in SCENARIOS if "unlock" not in s]


def is_available(scenario: dict[str, Any], owned_unlocks: set[str]) -> bool:
    """A scenario is playable if it's free or its unlock has been bought."""
    unlock = scenario.get("unlock")
    return unlock is None or unlock in owned_unlocks


def available_ids(owned_unlocks: set[str]) -> list[str]:
    return [s["id"] for s in SCENARIOS if is_available(s, owned_unlocks)]


def featured_story_id(subject: str, day: str, owned_unlocks: set[str]) -> str:
    """Deterministic "today's story" pick from the available pool — stable per (subject, day), so the
    Home screen can show a different featured arc each day ("today's different"). Pure."""
    pool = available_ids(owned_unlocks) or FREE_IDS
    ranked = sorted(pool, key=lambda sid: hashlib.sha256(f"{subject}:{day}:{sid}".encode()).hexdigest())
    return ranked[0]


async def build_story(
    level: str | None = None,
    context_override: str | None = None,
    scenario_id: str | None = None,
    lang: str | None = None,
) -> dict[str, Any]:
    """Assemble a mini-story: pick a curated scenario, then generate one exercise per beat.

    Each exercise is produced by `grammar.generate_exercise` (its own 3-retry + multiple-choice
    fallback), so a single bad generation degrades to a simpler card rather than breaking the set.
    `level` is locked across the whole story; the per-beat topic varies across the scenario's topics
    so the set isn't monotonous. `context_override`, if given, replaces the scenario's flavor context.
    `scenario_id` selects a specific arc (availability is enforced by the caller); omitted → random.
    """
    scenario = _BY_ID.get(scenario_id) if scenario_id else None
    if scenario is None:
        scenario = random.choice(SCENARIOS)
    context = context_override or scenario["context"]
    topics = scenario["topics"]

    # Beats are independent generations (the narrative thread is curated above, not model-made),
    # so run them concurrently — the story arrives in one generation's latency instead of three.
    exercises = await asyncio.gather(
        *(
            grammar.generate_exercise(
                topic=topics[i % len(topics)], level=level, ex_type=None, context=context, lang=lang
            )
            for i in range(STORY_LEN)
        )
    )
    beats: list[dict[str, Any]] = []
    for i, exercise in enumerate(exercises):
        narration = scenario["narration"][i] if i < len(scenario["narration"]) else ""
        beats.append({"narration": narration, "exercise": exercise})

    return {
        "id": scenario["id"],
        "title": scenario["title"],
        "intro": scenario["intro"],
        "level": grammar._cefr(level),
        "beats": beats,
    }
